frontend/models/ParticipantsForm.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace frontend\models;

use yii\db\ActiveRecord;
use Yii;

/**
 * This is the model class for table {{participants}}.
 *
 * @property string $participant
 * @property string $category
 */
class ParticipantsForm extends ActiveRecord {

    const
    SCENARIO_CREATE = 'create';
    const
    SCENARIO_UPDATE = 'update';

    public
    $currentUser;

    public
    function __construct () {
        $this->currentUser = Yii::$app->user->identity;
    }

//end __construct()

    /**
     * {@inheritdoc}
     */
    public static
    function tableName () {
        return 'participants';
    }

//end tableName()

    public
    function getUser () {
        return $this->hasOne(\common\models\User::className(), ['username' => 'participant']);
    }

//end getUser()

    public
    function scenarios () {
        return [
            self::SCENARIO_CREATE => [
                'participant',
                'category',
            ],
            self::SCENARIO_UPDATE => ['category'],
        ];
    }

//end scenarios()

    /**
     * {@inheritdoc}
     */
    public
    function rules () {
        return [
            [
                'participant',
                'required',
            ],
            [
                'participant', 'string', 'max' => 32
            ],
            [
                'category', 'string', 'max' => 255
            ],
            [
                'category', 'default', 'value' => 'uncategorized'
            ],
            [
                [
                    'participant',
                    'category',
                ], 'filter', 'filter' => 'trim'
            ],
            ['category', 'filter', 'filter' => function () {
                    // begins all words with Up letter
                    return ucwords($this->category);
                }
            ],
            [
                'participant', 'exist', 'targetAttribute' => 'username', 'targetClass' => '\common\models\User', 'message' => 'There is no such user in our database.'
            ],
            [
                'participant', 'unique', 'filter' => ['userId' => $this->userId], 'message' => 'Such participant already exists. You can only change category, or delete this participant.'
            ],
            [
                'participant', 'compare', 'compareValue' => $this->currentUser->username, 'operator' => '!=', 'message' => "You can't add yourself to participants.", 'on' => self::SCENARIO_CREATE
            ],
        ];
    }

//end rules()

    /**
     * {@inheritdoc}
     */
    public
    function attributeLabels () {
        return [
            'participant' => 'Participant',
            'category' => 'Category',
            'user.first_name' => 'First Name',
            'user.last_name' => 'Last Name',
            'user.country' => 'Country',
            'user.area' => 'Area',
            'user.city' => 'City',
            'user.photo' => 'User photo',
        ];
    }

//end attributeLabels()
}

//end class

frontend/controllers/ParticipantsController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace frontend\controllers;

use Yii;
use common\models\User;
use common\traits\CommonTrait;
use frontend\models\ParticipantsForm;
use frontend\models\SearchParticipantsForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
// use yii\helpers\Url;

/**
 * ParticipantsController implements the CRUD actions for ParticipantsForm model.
 */
class ParticipantsController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

//end behaviors()

    /**
     * Lists all ParticipantsForm models.
     *
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new SearchParticipantsForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render(
        'index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]
        );
    }

//end actionIndex()

    /**
     * Displays a single ParticipantsForm model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id, $redirectFromUsersSearch = false) {
        $model = $this->findModel($id);
        CommonTrait::setGlobalsStatus($model->user->status);

        return $this->render(
        'view', [
            'model' => $model,
            'userPhoto' => $model->user->photo,
            'redirectFromUsersSearch' => $redirectFromUsersSearch,
        ]
        );
    }

//end actionView()

    /**
     * Creates a new ParticipantsForm model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @return mixed
     */
    public function actionCreate($id = null, $redirectFromUsersSearch = false) {
        $model = new ParticipantsForm();
        $model->scenario = ParticipantsForm::SCENARIO_CREATE;
        $model->userId = Yii::$app->user->getId();

        if ($id !== null) {
            $userToAdd = User::findIdentity($id);
            $model->participant = $userToAdd->username;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            Yii::$app->session->setFlash('success', 'Your participant was successfully created.');

            return $this->redirect(['view', 'id' => $model->id, 'redirectFromUsersSearch' => $redirectFromUsersSearch]);
        } else {
            return $this->render(
            'create', ['model' => $model, 'redirectFromUsersSearch' => $redirectFromUsersSearch]
            );
        }
    }

//end actionCreate()

    /**
     * Updates an existing ParticipantsForm model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionUpdate($id, $redirectFromUsersSearch = false) {
        $model = $this->findModel($id);
        $model->scenario = ParticipantsForm::SCENARIO_UPDATE;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Your participant record was successfully updated.');
            return $this->redirect(['view', 'id' => $model->id, 'redirectFromUsersSearch' => $redirectFromUsersSearch]);
        } else {
            return $this->render(
            'update', ['model' => $model, 'redirectFromUsersSearch' => $redirectFromUsersSearch]
            );
        }
    }

//end actionUpdate()

    /**
     * Deletes an existing ParticipantsForm model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionDelete($id, $redirectFromUsersSearch = false) {
        $this->findModel($id)->delete();
        if (!$redirectFromUsersSearch) {
            return $this->redirect(['index']);
        } else {
            return $this->redirect(['/search-users/index']);
        }
    }

//end actionDelete()

    /**
     * Finds the ParticipantsForm model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return ParticipantsForm the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = ParticipantsForm::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

//end findModel()
}

//end class

frontend/views/participants/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ParticipantsForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="participants-form-form">
    <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a role="tab" data-toggle="tab">You participants</a></li>
        <li><?= Html::a('Find participants', ['search-users/index']) ?></li>
    </ul></br>
    <?php $form = ActiveForm::begin(); ?>

    <?php if ($model->isNewRecord): ?>
        <?= $form->field($model, 'participant')->label('Participant username:')->textInput(['maxlength' => true]) ?>
    <?php endif; ?>

    <?= $form->field($model, 'category')->textInput(['maxlength' => true])->label('Please enter category for the participant ' . $model->participant . ':')->hint('If the field will remain blank the default category "Uncategorized" will be assigned.') ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-main-red']) ?>
        
        <?php if (!$redirectFromUsersSearch): ?>
            <?= Html::a('Cancel', ['/participants/index'], ['class' => 'btn btn-main-white']) ?>
        <?php else: ?>
            <?= Html::a('Cancel', ['/search-users/index'], ['class' => 'btn btn-main-white']) ?>
        <?php endif; ?>
    
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/participants/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\SearchParticipants */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="participants-form-search">

    <?php
    $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]);
    ?>

    <?= $form->field($model, 'participant') ?>

    <?= $form->field($model, 'category') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-main-red']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-main-white']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/participants/create.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\ParticipantsForm */

$this->title = 'Create new participant:';
$this->params['breadcrumbs'][] = ['label' => 'Your participants', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="friends-form-create">
    <div class="row">
        <div class="col-xs-12 col-md-8">

            <?=
            $this->render('_form', [
                'model' => $model,
                'redirectFromUsersSearch' => $redirectFromUsersSearch,
            ])
            ?>

        </div>
        <div align=right class="col-xs-12 col-md-4" style="class: img-responsive">
            <p>
                <a href="http://donate.unhcr.org/international/general" title="UN Refugee Agency" target='_blank'>
                    <img src="/img/banners/UNHCR/WRD2015-300x600-V2-Hany.jpg" alt="UN Refugee Agency" >
                </a>
            </p>
        </div>
    </div>
</div>

frontend/views/participants/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\SearchParticipants */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Your participants:';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="participants-form-index" align=justify style="width:100%">
    <p>All users in the game divided in to two groups - your participants (blocked users also calculates as participants with category 'Blocked'), and all other users. User can be only in one of this groups at the same time.</p>
    <ul class="nav nav-tabs" role="tablist">
        <li class="active"><a role="tab" data-toggle="tab">Your participants</a></li>
        <li><?= Html::a('Search users', ['search-users/index']) ?></li>
    </ul>
    </br>
    <p>You can order results ascending or descending by pressing to the title links. To find participant(s) - type (can be grouped and not ended) in the blank fields, after each field press Enter. To reset form - press Reset button. To view user profile - press 'eye' tool, to block user - change his or her category to blocked or Blocked by pressing 'pen' tool. In same manner to unblock user - just change or delete category. Note! If you'll delete blocked user from participants he/she will be unblocked.</p>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'tableOptions' => [
            'class' => 'table table-bordered'
        ],
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
            ],
            [
                'attribute' => 'user.photo',
                'format' => 'raw',
                'value' => function($data) {
                    $tmp = $data->user->photo;
                    $id = $data->id;
                    return Html::a(Html::img("data:image/png;base64, $tmp", ['alt' => 'User photo', 'class' => 'img-responsive']), ['/participants/view', 'id' => $id]);
                },
            ],
            'participant',
            'category',
            'user.first_name',
            'user.last_name',
            'user.country:ntext',
            'user.area:ntext',
            'user.city',
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Tools',
                'template' => '{view}&nbsp{update}&nbsp{message}&nbsp{delete}',
                'buttons' => [
                    'message' => function ($url, $model) {
                        return Html::a(
                        '<span class="glyphicon glyphicon-comment" title="Message"></span>', $url);
                    },
                ],
            ],
        ],
    ]);
    ?>

    <p>
        <?= Html::a('Create new participant', ['create'], ['class' => 'btn btn-main-red']) ?>
        <?= Html::a('Reset', ['index'], ['class' => 'btn btn-main-white']) ?>
        <?= Html::a('Cancel', ['/site/index'], ['class' => 'btn btn-main-white']) ?>
    </p>
</div>

frontend/views/participants/update.php
<?php
/* @var $this yii\web\View */
/* @var $model app\models\ParticipantsForm */

$this->params['breadcrumbs'][] = ['label' => 'Your participants', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update participant:';
?>

<div class="participants-form-update">
    <div class="row">
        <div class="col-xs-12 col-md-8">

            <?=
            $this->render('_form', [
                'model' => $model,
                'redirectFromUsersSearch' => $redirectFromUsersSearch,
            ])
            ?>

        </div>
        <div align=right class="col-xs-12 col-md-4" style="class: img-responsive">
            <p>
                <a href="http://donate.unhcr.org/international/general" title="UN Refugee Agency" target='_blank'>
                    <img src="/img/banners/UNHCR/WRD2015-300x600-V2-Ibrahim.jpg" alt="UN Refugee Agency" >
                </a>
            </p>
        </div>
    </div>
</div>

frontend/views/participants/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ParticipantsForm */

$this->params['breadcrumbs'][] = ['label' => 'Your participants', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'View participant:';
?>

<div class="participants-form-view">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div align=center>
                <?= Html::img("data:image/png;base64, $userPhoto", ['alt' => 'User photo', 'class' => 'img-responsive']) ?>
            </div>
            <div>
                </br>

                <?php if ($model->user->show_email == 0) : ?>

                    <?=
                    DetailView::widget([
                        'options' => [
                            'class' => 'table table-bordered'
                        ],
                        'model' => $model->user,
                        'attributes' => [
                            'username',
                            [
                                'attribute' => 'status',
                                'value' => Html::tag('font', Html::encode($GLOBALS['userStatus']), ['color' => $GLOBALS['statusColor']]),
                                'format' => 'raw',
                            ],
                            'created_at:datetime',
                            'updated_at:datetime',
                            'first_name',
                            'last_name',
                            'sex',
                            'birth_date:date',
                            'country',
                            'area',
                            'city',
                        ],
                    ])
                    ?>

                <?php else : ?>

                    <?=
                    DetailView::widget([
                        'options' => [
                            'class' => 'table table-bordered'
                        ],
                        'model' => $model->user,
                        'attributes' => [
                            'username',
                            'email:email',
                            [
                                'attribute' => 'status',
                                'value' => Html::tag('font', Html::encode($GLOBALS['userStatus']), ['color' => $GLOBALS['statusColor']]),
                                'format' => 'raw',
                            ],
                            'created_at:datetime',
                            'updated_at:datetime',
                            'first_name',
                            'last_name',
                            'sex',
                            'birth_date:date',
                            'country',
                            'area',
                            'city',
                        ],
                    ])
                    ?>

                <?php endif; ?>
            </div>
            <div>
                <?=
                DetailView::widget([
                    'options' => [
                        'class' => 'table table-bordered'
                    ],
                    'model' => $model,
                    'attributes' => [
                        'participant',
                        'category',
                    ],
                ])
                ?>
            </div>

            <div class="form-group">
                <p>
                    <?= Html::a('Update', ['update', 'id' => $model->id, 'redirectFromUsersSearch' => $redirectFromUsersSearch], ['class' => 'btn btn-main-red']) ?>
                    <?=
                    Html::a('Delete', ['delete', 'id' => $model->id, 'redirectFromUsersSearch' => $redirectFromUsersSearch], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ])
                    ?>
                    
                    <?php if (!$redirectFromUsersSearch): ?>
                        <?= Html::a('Cancel', ['/participants/index'], ['class' => 'btn btn-main-white']) ?>
                    <?php else: ?>
                        <?= Html::a('Cancel', ['/search-users/index'], ['class' => 'btn btn-main-white']) ?>
                    <?php endif; ?>
                    
                </p>
            </div>
        </div>
        <div align=right class="col-xs-12 col-md-4" style="class: img-responsive">
            <p>
                <a href="http://donate.unhcr.org/international/general" title="UN Refugee Agency" target='_blank'>
                    <img src="/img/banners/UNHCR/WRD2015-300x600-V2-Nader.jpg" alt="UN Refugee Agency" >
                </a>
            </p>
        </div>
        <div align=right class="hidden-xs col-md-4" style="class: img-responsive">
            <p>
                <a href="http://www.unhcr.org" title="UN Refugee Agency" target='_blank'>
                    <img src="/img/banners/UNHCR/WRD2015-300x600-V2-Katia.jpg" alt="UN Refugee Agency" >
                </a>
            </p>
        </div>
    </div>
</div>