backend/controllers/FakerController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace backend\controllers;

use Yii;
use Faker;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\helpers\FileHelper;
use common\models\User;
use common\traits\CommonTrait;
use yii\imagine\Image;

define('__VENDOR__', dirname(dirname(__DIR__)));
require_once(__VENDOR__ . "/vendor/fzaninotto/faker/src/autoload.php");

/**
 * Truncate tables {{user}}, {{participants}}, {{userauthlog}} and populates
 * {{user} with 33 fakes users.
 */
class FakerController extends Controller {

    /**
     * Only root access. Admins - denied!
     * 
    
    public function behaviors () {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                        [
                        'allow' => true,
                        'roles' => ['root'],
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    throw new \Exception('You have no permission to perfom this action!');
                },
            ],
        ];
    }
*/
    /**
     * Populates database with faker users. Part 1, because shared hosting
     * server php timeout.
     * 
     * @return goHome()
     */
    public function actionFaker1() {
        $faker = Faker\Factory::create();
        $faker->seed(1234); // ucomment for the same fake data
        //Yii::$app->db->createCommand()->truncateTable('user')->execute();
        //Yii::$app->db->createCommand()->truncateTable('participants')->execute();
        //Yii::$app->db->createCommand()->truncateTable('userauthlog')->execute();
        FileHelper::copyDirectory(dirname(__DIR__) . '/data/ForFaker', dirname(__DIR__) . '/data/FakerPicsTmp');
        for ($i = 0; $i < 10; $i++) {
            $user = new User();
            $user->username = $faker->userName;
            $user->email = $faker->email;
            $user->first_name = $faker->firstName;
            $user->last_name = $faker->lastName;
            $user->sex = $faker->randomElement($array = array('Female', 'Man', 'Other gender'));
            $user->birth_date = $faker->date($format = 'Y-m-d', $max = '-12 years');
            $user->country = $faker->country;
            $user->area = $faker->state;
            $user->city = $faker->city;
            $user->password_hash = Yii::$app->getSecurity()->generatePasswordHash('Demo2016');
            $user->secret_question = 'Your mother maiden name?';
            $user->secret_question_answer = Yii::$app->getSecurity()->generatePasswordHash('Blank');
            $user->auth_key = Yii::$app->getSecurity()->generateRandomString();
            $user->status = 10;
            $user->photo_extension = 'jpg';
            if ($i%2 != 0) {
                $user->show_email = 1;
                $user->photo_verified = 1;
            } else {
                $user->photo_verified = 0;
            }

            $filename = dirname(__DIR__) . '/data/FakerPicsTmp/' . "$i" . '.' . 'jpg';
            Image::thumbnail($filename, $width = 550, $height = null)->save($filename);
            CommonTrait::setPhotoBorder($user, $filename);
            Image::watermark($filename, $_SERVER['DOCUMENT_ROOT'] . '/img/watermark.png', [20, 20])->save($filename);
            CommonTrait::prepareImageForDatabase($user, $filename);
            $user->save();
        }
        Yii::$app->session->setFlash('success', 'Database populated! First part.');

        return $this->goHome();
    }
    
    /**
     * Populates database with faker users. Part 2, because shared hosting
     * server php timeout.
     * 
     * @return goHome()
     */    
    public function actionFaker2() {
        $faker = Faker\Factory::create();
        $faker->seed(6789); // ucomment for the same fake data
        for ($i = 10; $i < 20; ++$i) {
            $user = new User();
            $user->username = $faker->userName;
            $user->email = $faker->email;
            $user->first_name = $faker->firstName;
            $user->last_name = $faker->lastName;
            $user->sex = $faker->randomElement($array = array('Female', 'Man', 'Other gender'));
            $user->birth_date = $faker->date($format = 'Y-m-d', $max = '-12 years');
            $user->country = $faker->country;
            $user->area = $faker->state;
            $user->city = $faker->city;
            $user->password_hash = Yii::$app->getSecurity()->generatePasswordHash('Demo2016');
            $user->secret_question = 'Your mother maiden name?';
            $user->secret_question_answer = Yii::$app->getSecurity()->generatePasswordHash('Blank');
            $user->auth_key = Yii::$app->getSecurity()->generateRandomString();
            $user->status = 10;
            $user->photo_extension = 'jpg';
            if ($i%2 != 0) {
                $user->show_email = 1;
                $user->photo_verified = 1;
            } else {
                $user->photo_verified = 0;
            }

            $filename = dirname(__DIR__) . '/data/FakerPicsTmp/' . "$i" . '.' . 'jpg';
            Image::thumbnail($filename, $width = 550, $height = null)->save($filename);
            CommonTrait::setPhotoBorder($user, $filename);
            Image::watermark($filename, $_SERVER['DOCUMENT_ROOT'] . '/img/watermark.png', [20, 20])->save($filename);
            CommonTrait::prepareImageForDatabase($user, $filename);
            $user->save();
        }

        Yii::$app->session->setFlash('success', 'Database populated! Second part.');

        return $this->goHome();
    }
    
        /**
     * Populates database with faker users. Part 3, because shared hosting
     * server php timeout.
     * 
     * @return goHome()
     */
    public function actionFaker3() {
        $faker = Faker\Factory::create();
        $faker->seed(5678); // ucomment for the same fake data
        for ($i = 20; $i < 32; ++$i) {
            $user = new User();
            $user->username = $faker->userName;
            $user->email = $faker->email;
            $user->first_name = $faker->firstName;
            $user->last_name = $faker->lastName;
            $user->sex = $faker->randomElement($array = array('Female', 'Man', 'Other gender'));
            $user->birth_date = $faker->date($format = 'Y-m-d', $max = '-12 years');
            $user->country = $faker->country;
            $user->area = $faker->state;
            $user->city = $faker->city;
            $user->password_hash = Yii::$app->getSecurity()->generatePasswordHash('Demo2016');
            $user->secret_question = 'Your mother maiden name?';
            $user->secret_question_answer = Yii::$app->getSecurity()->generatePasswordHash('Blank');
            $user->auth_key = Yii::$app->getSecurity()->generateRandomString();
            $user->status = 33;
            $user->photo_extension = 'jpg';
            if ($i%2 != 0) {
                $user->show_email = 1;
            }

            $filename = dirname(__DIR__) . '/data/FakerPicsTmp/' . "$i" . '.' . 'jpg';
            Image::thumbnail($filename, $width = 550, $height = null)->save($filename);
            CommonTrait::setPhotoBorder($user, $filename);
            Image::watermark($filename, $_SERVER['DOCUMENT_ROOT'] . '/img/watermark.png', [20, 20])->save($filename);
            CommonTrait::prepareImageForDatabase($user, $filename);
            $user->save();
        }

        FileHelper::removeDirectory(dirname(__DIR__) . '/data/FakerPicsTmp');
        Yii::$app->session->setFlash('success', 'Database populated! Third part.');

        return $this->goHome();
    }
    
    /** 
     * Populates users participants
     * 
     * @return goHome()
     */
    public function actionFakerParticipants() {
        $faker = Faker\Factory::create();
        $users = User::find()->all();
        for ($i = 0; $i < 32; $i++) {
            for ($j = 0; $j < 32; $j++) {
                if ($j != $i) {
                    $users[$i]['participants'] = $users[$i]['participants'] . $users[$j]['username'] . ':' . $faker->randomElement($array = array('Family', 'Friends', 'Сolleague', 'Team1', 'Team2', 'Blocked')) . ':';
                }
            }
            $users[$i]['participants'] = substr($users[$i]['participants'], 0, -1);
            $users[$i]->save();
        }
        Yii::$app->session->setFlash('success', 'Database populated! Participants part.');

        return $this->goHome();
    }

    /**
     * Create rumatakira admin user
     * 
     * @return goHome()
     */
    public function actionFakerRumatakira() {
        $user = new User();
        $user->username = 'rumatakira';
        $user->email = 'support@mafiaonlinegame.com';
        $user->first_name = 'Kira';
        $user->last_name = 'Rumata';
        $user->sex = 'Female';
        $user->birth_date = '1973-11-20';
        $user->country = 'Montenegro';
        $user->area = 'Budva';
        $user->city = 'Budva';
        $user->password_hash = Yii::$app->getSecurity()->generatePasswordHash('Medvezhonka08'); // set the password !!!
        $user->secret_question = 'Your favorite meal?';
        $user->secret_question_answer = Yii::$app->getSecurity()->generatePasswordHash(''); // set the answer !!!
        $user->auth_key = Yii::$app->getSecurity()->generateRandomString();
        $user->status = 33;
        $user->photo_extension = 'jpg';
        $filename = $_SERVER['DOCUMENT_ROOT'] . '/img/avatar_woman.jpg';
        CommonTrait::prepareImageForDatabase($user, $filename);
        $user->save();
        Yii::$app->session->setFlash('success', 'Rumatakira admin user created.');

        return $this->goHome();
    }
    
}

backend/controllers/SiteController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace backend\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Backend site controller.
 */
class SiteController extends Controller {
/*
    public function behaviors () {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                        [
                        'allow' => true,
                        'roles' => ['root', 'admin'],
                    ],
                ],
                'denyCallback' => function ($rule, $action) {
                    throw new \Exception('You have no permission to access this area!');
                },
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
 */

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * ! This is not mistake !
     * Set border to template user photos according user sex.
     */
    public
    function actionSetPhotoBorders() {
        //copy files from main avatar
        copy($_SERVER['DOCUMENT_ROOT'] . '/img/avatar.jpg', $_SERVER['DOCUMENT_ROOT'] . '/img/avatar_woman.jpg');
        copy($_SERVER['DOCUMENT_ROOT'] . '/img/avatar.jpg', $_SERVER['DOCUMENT_ROOT'] . '/img/avatar_man.jpg');
        copy($_SERVER['DOCUMENT_ROOT'] . '/img/avatar.jpg', $_SERVER['DOCUMENT_ROOT'] . '/img/avatar_other_gender.jpg');
        // set borders and save files
        \yii\imagine\Image::frame($_SERVER['DOCUMENT_ROOT'] . '/img/avatar_woman.jpg', 16, '#FF99CC')->save($_SERVER['DOCUMENT_ROOT'] . '/img/avatar_woman.jpg');
        \yii\imagine\Image::frame($_SERVER['DOCUMENT_ROOT'] . '/img/avatar_man.jpg', 16, '#0066FF')->save($_SERVER['DOCUMENT_ROOT'] . '/img/avatar_man.jpg');
        \yii\imagine\Image::frame($_SERVER['DOCUMENT_ROOT'] . '/img/avatar_other_gender.jpg', 16, '#CC00FF')->save($_SERVER['DOCUMENT_ROOT'] . '/img/avatar_other_gender.jpg');

        Yii::$app->session->setFlash('success', 'Done!');
        return $this->render('index');
    }

}

backend/controllers/SitemapController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use samdark\sitemap\Sitemap;
use samdark\sitemap\Index;

/**
 * Creates sitemap.xml
 */
class SitemapController extends Controller {

    public function actionSitemap() {

        // create sitemap
        $sitemap = new Sitemap(Yii::getAlias('@webroot/../sitemap.xml'));

        // add some URLs
        $sitemap->addItem('http://http://mafiaonlinegame.com/index.php?r=site%2Findex', time(), Sitemap::DAILY);
        $sitemap->addItem('http://http://mafiaonlinegame.com/index.php?r=site%2Flogin', time(), Sitemap::DAILY);
        $sitemap->addItem('http://http://mafiaonlinegame.com/index.php?r=site%2Fsignup', time(), Sitemap::DAILY);
        $sitemap->addItem('http://mafiaonlinegame.com/index.php?r=site%2Fcontact', time(), Sitemap::DAILY);
        $sitemap->addItem('http://mafiaonlinegame.com/index.php?r=site%2Fsite-map', time(), Sitemap::DAILY);

        // write it
        $sitemap->write();

        Yii::$app->session->setFlash('success', 'Sitemap file created!');

        return $this->goHome();

        /*
          // add some URLs
          $sitemap->addItem('http://example.com/mylink1');
          $sitemap->addItem('http://example.com/mylink2', time());
          $sitemap->addItem('http://example.com/mylink3', time(), Sitemap::HOURLY);
          $sitemap->addItem('http://example.com/mylink4', time(), Sitemap::DAILY, 0.3);

          // get URLs of sitemaps written
          $sitemapFileUrls = $sitemap->getSitemapUrls('http://example.com/');

          // create sitemap for static files
          $staticSitemap = new Sitemap(__DIR__ . '/sitemap_static.xml');

          // add some URLs
          $staticSitemap->addItem('http://example.com/about');
          $staticSitemap->addItem('http://example.com/tos');
          $staticSitemap->addItem('http://example.com/jobs');

          // write it
          $staticSitemap->write();

          // get URLs of sitemaps written
          $staticSitemapUrls = $staticSitemap->getSitemapUrls('http://example.com/');

          // create sitemap index file
          $index = new Index(__DIR__ . '/sitemap_index.xml');

          // add URLs
          foreach ($sitemapFileUrls as $sitemapUrl) {
          $index->addSitemap($sitemapUrl);
          }

          // add more URLs
          foreach ($staticSitemapUrls as $sitemapUrl) {
          $index->addSitemap($sitemapUrl);
          }

          // write it
          $index->write();
         */
    }

}

backend/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use common\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => 'Mafia online role game',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);

            $menuItems[] = ['label' => 'Backend', 'url' => ['/site/index']];
            $menuItems[] = ['label' => 'Frontend', 'url' => '@web/../'];
            $menuItems[] = [
                'label' => 'Tests',
                'items' => [
                    [
                        'label' => 'Faker database population1',
                        'url' => ['/faker/faker1'],
                    ],
                    [
                        'label' => 'Faker database population2',
                        'url' => ['/faker/faker2'],
                    ],
                    [
                        'label' => 'Faker database population3',
                        'url' => ['/faker/faker3'],
                    ],
                    [
                        'label' => 'Faker participants population',
                        'url' => ['/faker/faker-participants'],
                    ],
                    [
                        'label' => 'Create rumatakira admin user',
                        'url' => ['/faker/faker-rumatakira'],
                    ],
                    [
                        'label' => 'Set borders to template user photos',
                        'url' => ['/site/set-photo-borders'],
                    ],
                ],
            ];
            $menuItems[] = [
                'label' => 'Site',
                'items' => [
                    [
                        'label' => 'Create Sitemap',
                        'url' => ['/sitemap/sitemap'],
                    ],
                ],
            ];
            $menuItems[] = [
                'label' => 'Database',
                'items' => [
                    [
                        'label' => 'Clean Database',
                        'url' => ['/sitemap/sitemap'],
                    ],
                ],
            ];

            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

                <p class="pull-right"><?= Yii::powered() ?></p>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>