frontend/controllers/SearchUsersController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace frontend\controllers;

use Yii;
use common\models\User;
use common\traits\CommonTrait;
use frontend\models\SearchUsersForm;
use frontend\models\ParticipantsForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * SearchController implements the CRUD actions for UserSearch model.
 */
class SearchUsersController extends Controller {

    /**
     * Lists all UserSearch models.
     *
     * @return mixed
     */
    public function actionIndex($viewOnlyPremium = null, $viewOnlyApprovedPhoto = null, $viewOnlyWithPhoto = null) {
        $additionalParams = ['viewOnlyPremium' => $viewOnlyPremium, 'viewOnlyApprovedPhoto' => $viewOnlyApprovedPhoto, 'viewOnlyWithPhoto' => $viewOnlyWithPhoto];
        $searchModel = new SearchUsersForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $additionalParams);

        return $this->render(
        'index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]
        );
    }

//end actionIndex()

    /**
     * Displays a single UserSearch model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id) {
        $user = $this->findModel($id);
        CommonTrait::setGlobalsStatus($user->status);

        return $this->render(
        'view', ['model' => $user]
        );
    }

//end actionView()

    /**
     * Add a single UserSearch model to the table participant.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionAdd($id) {
        return $this->redirect(['/participants/create', 'id' => $id, 'redirectFromUsersSearch' => true]);
    }

//end actionAdd()

    /**
     * Block a single UserSearch model by adding to the table participant with category 'Blocked'.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionBlock($id) {
        $userToBlock = $this->findModel($id);
        $model = new ParticipantsForm();
        $model->scenario = ParticipantsForm::SCENARIO_CREATE;
        $model->participant = $userToBlock->username;
        $model->userId = Yii::$app->user->getId();
        $model->category = 'Blocked';
        try {
            $model->save();
            Yii::$app->session->setFlash('success', "User $userToBlock->username was blocked and can't be able to play or communicate with you.");
        } catch (ErrorException $e) {
            Yii::$app->session->setFlash('error', 'Oops... Something went wrong. There was server error during blocking user. Try again later. If the mistake will remain - please contact us.');

            return false;
        }

        return $this->redirect(['index']);
    }

//end actionBlock()

    /**
     * Finds the UserSearch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return UserSearch the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

//end findModel()
}

//end class

frontend/controllers/SiteController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace frontend\controllers;

use Yii;
use common\models\User;
use common\models\LoginForm;
use common\traits\CommonTrait;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\ChangePasswordForm;
use frontend\models\SignupForm;
use frontend\models\EditProfileForm;
use frontend\models\UpdatePhotoForm;
use frontend\models\DeleteAccountForm;
use frontend\models\ContactForm;
use frontend\models\SettingsForm;
use yii\base\InvalidParamException;
use yii\base\ErrorException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller.
 */
class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'login',
                    'logout',
                    'signup',
                ],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [
                            'login',
                            'signup',
                        ],
                        'allow' => false,
                        'ips' => CommonTrait::getBlockedIPs(),
                    // NOTE! With Yii 2.0.7 working only IPv6 addresses
                    ],
                    [
                        'actions' => [
                            'login',
                            'signup',
                        ],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

//end behaviors()

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => ['class' => 'yii\web\ErrorAction'],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

//end actions()

    /**
     * Redirecting user to the Signup if guest, or to the Gameplay page.
     */
    public function actionPlay() {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect(['signup']);
        } else {
            return $this->redirect(['profile']);
        }
    }

//end actionPlay()

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex() {
        return $this->render('index');
    }

//end actionIndex()

    /**
     * Displays different site map pages for guests and users.
     *
     * @return mixed
     */
    public function actionSiteMap() {
        if (\Yii::$app->user->isGuest) {
            return $this->render('siteMapGuest');
        } else {
            return $this->render('siteMapUser');
        }
    }

//end actionSiteMap()

    /**
     * Displays contact page for guests.
     *
     * @return mixed
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(\Yii::$app->params['supportEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render(
            'contact', ['model' => $model]
            );
        }
    }

//end actionContact()

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) and $model->login()) {
            $user = Yii::$app->user->getIdentity();
            CommonTrait::setUserRoles($user);
            try {
                CommonTrait::participantsExplode($user);
                if ($user->status == 0) {
                    CommonTrait::statusRestore($user);
                    $user->save();
                    Yii::$app->session->setFlash('success', 'Welcome back ' . $user->username . '! Your account was restored!');
                }
            } catch (ErrorException $e) {
                $flash = array('error' => 'Oops... Something went wrong. There was server error during preparing operations. Try to reload the main page and login again. If the mistake will remain - please contact us.');

                self::actionLogout($flash);
            }

            return $this->goBack();
        } else {
            return $this->render(
            'login', ['model' => $model]
            );
        }//end if
    }

//end actionLogin()

    /**
     * Logs out the current user. Delete all rows with
     * current user->id from {{participants}}, i
     * mplode them and save to {{user}} [[participants]].
     *
     * @return mixed
     */
    public function actionLogout($flash = null) {
        $user = Yii::$app->user->getIdentity();
        if (CommonTrait::participantsImplode($user)) {
            $user->save();
        }

        Yii::$app->user->logout();
        if ($flash != null) {
            Yii::$app->session->setFlash(key($flash), current($flash));
        }

        return $this->goHome();
    }

//end actionLogout()

    /**
     * Prepare ActiveRecord object and renders user profile.
     */
    public function actionProfile() {
        $user = Yii::$app->user->identity;
        CommonTrait::setGlobalsStatus($user->status);


        return $this->render(
        'profile', ['model' => $user]
        );
    }

//end actionProfile()

    /**
     * Updates user profile.
     *
     * @return mixed
     */
    public function actionEditProfile() {
        $model = new EditProfileForm();
        if ($model->load(Yii::$app->request->post())) {
            $changesArray = $model->editProfile();

            if ($changesArray != null) {
                if ($changesArray['dataChanged']) {
                    if (!$changesArray['emailChanged'] and ! $changesArray['sexChanged']) {
                        Yii::$app->session->setFlash('success', 'Great! Your profile has been updated.');

                        return $this->redirect(['profile']);
                    } else if (!$changesArray['emailChanged'] and $changesArray['sexChanged']) {

                        return self::actionDeletePhoto();
                    }
                }

                return $this->redirect(['profile']);
            }
        }

        return $this->render(
        'editProfile', ['model' => $model]
        );
    }

//end actionEditProfile()

    /**
     * Mark user account for deletion.
     * 
     * @return mixed
     */
    public function actionDeleteAccount() {
        $model = new DeleteAccountForm();
        if ($model->load(Yii::$app->request->post()) && $model->deleteAccount()) {
            return self::actionLogout(['success' => 'Your account has been marked for deletion and will be deleted during next database cleaning procedure. Normally it happens monthly at the last days. Until that, you can restore your account by simply logging to the site.']);
        }

        return $this->render(
        'deleteAccount', ['model' => $model]
        );
    }
    
//end actionDeleteAccount()
    
    /**
     * Replace user photo in database with default image.
     * 
     * @return redirect /site/update-photo
     */
    public function actionDeletePhoto() {
        $user = Yii::$app->user->identity;
        CommonTrait::setBasePhoto($user);
        $user->save();

        return $this->redirect(['/site/update-photo']);
    }

//end actionDeletePhoto()

    /**
     * Updates user photo.
     *
     * @return mixed
     */
    public function actionUpdatePhoto() {
        $model = new UpdatePhotoForm();
        if ($model->load(Yii::$app->request->post()) and $model->editPhoto()) {
            Yii::$app->session->setFlash('success', 'Great! Your photo has been updated. In some browsers you need to refresh the page with cache cleaning (usually Ctrl-F5) to see all changes. ');

            return $this->refresh();
        }

        return $this->render(
        'updatePhoto', [
            'model' => $model,
            'userPhoto' => $model->user->photo
        ]
        );
    }

//end actionUpdatePhoto()



    /**
     * Renders user profile.
     * 
     * @return mixed
     */
    public function actionSettings() {
        $model = new SettingsForm();
        if ($model->load(Yii::$app->request->post()) && $model->updateSettings()) {
            return $this->refresh();
        }

        return $this->render(
        'settings', ['model' => $model]
        );
    }

//end actionSettings()

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                // if (Yii::$app->getUser()->login($user)) {
                if ($model->sendEmail($user)) {
                    $validateLink = Yii::$app->urlManager->createAbsoluteUrl(['site/resend-email', 'id' => $user->id, 'token' => $user->auth_key]);

frontend/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            if (Yii::$app->user->isGuest) {
                NavBar::begin([
                    'brandLabel' => Html::img('@web/img/main_logo.png', ['class' => 'img-responsive', 'style' => 'vertical-align: baseline; width: auto; height: 50px; padding: 0px; margin-top: -15px;']),
                    'brandUrl' => Yii::$app->homeUrl,
                    'options' => [
                        'class' => 'navbar-default navbar-fixed-top',
                    ],
                ]);
            } else {
                $user = Yii::$app->user->getIdentity();
                NavBar::begin([
                    'brandLabel' => Html::img("data:image/png;base64, $user->photo", ['class' => 'img-responsive', 'style' => 'vertical-align: baseline; width: auto; height: 50px; padding: 0px; margin-top: -15px;']),
                    'brandUrl' => ['/site/profile'],
                    'options' => [
                        'class' => 'navbar-default navbar-fixed-top',
                    ],
                ]);
            }
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Play the game', 'url' => ['/site/signup']];
            } else {
                $menuItems[] = ['label' => 'Play the game', 'url' => '@mafiaGamePlay'];
            }
            $menuItems[] = ['label' => 'Home', 'url' => ['/site/index']];
            $menuItems[] = [
                'label' => 'About',
                'items' => [
                    [
                        'label' => 'Our mission',
                        'url' => '@mafiaSiteMission',
                        'linkOptions' => ['target' => '_blank'],
                    ],
                    [
                        'label' => 'About us',
                        'url' => '@mafiaSiteAbout',
                        'linkOptions' => ['target' => '_blank'],
                    ],
                    [
                        'label' => 'Site map',
                        'url' => ['/site/site-map'],
                    ],
                ],
            ];
            $menuItems[] = [
                'label' => 'Rules',
                'items' => [
                    [
                        'label' => 'Site rules',
                        'url' => '@mafiaSiteRules',
                        'linkOptions' => ['target' => '_blank'],
                    ],
                    [
                        'label' => 'Game rules',
                        'url' => '@mafiaGameRules',
                        'linkOptions' => ['target' => '_blank'],
                    ],
                ],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = [
                    'label' => 'Contact us',
                    'items' => [
                        [
                            'label' => 'Guest contact form',
                            'url' => ['/site/contact'],
                        ],
                    ],
                ];
            } else {
                $menuItems[] = [
                    'label' => 'Contact us',
                    'items' => [
                        [
                            'label' => 'Contact us',
                            'url' => '@mafiaSiteForum',
                            'linkOptions' => ['target' => '_blank'],
                        ],
                        [
                            'label' => 'Report a bug',
                            'url' => '@mafiaSiteBugs',
                            'linkOptions' => ['target' => '_blank'],
                        ],
                    ],
                ];
            }
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']]; //, 'visible' => Yii::$app->user->isGuest];
                $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']]; //, 'visible' => Yii::$app->user->isGuest];
            } else {
                $menuItems[] = [
                    'label' => 'Account',
                    'items' => [
                        [
                            'label' => 'Profile',
                            'url' => ['/site/profile'],
                        ],
                        [
                            'label' => 'Settings',
                            'url' => ['/site/settings'],
                        ],
                        [
                            'label' => 'Participants',
                            'url' => ['/participants/index'],
                        ],
                        [
                            'label' => 'Seach users',
                            'url' => ['/search-users/index'],
                        ],
                        [
                            'label' => 'Messages',
                            'url' => ['/site/messages'],
                        ],
                        [
                            'label' => 'Forum',
                            'url' => '@mafiaSiteForum',
                            'linkOptions' => ['target' => '_blank'],
                        ],
                        '<li class="divider"></li>',
                        [
                            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                            'url' => ['/site/logout'],
                            'linkOptions' => ['data-method' => 'post'],
                        ],
                    ],
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);

            NavBar::end();
            ?>

            <div class="container">
                <?=
                Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ])
                ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <p class="pull-left">&copy;&nbsp;<?= date('Y') ?>&nbsp;&nbsp;
                    <a href="https://bitbucket.org/rumatakira/">Kiryl Lapchynski</a> (full stack),&nbsp;
                    <a href="https://www.facebook.com/ksenia.sorokina.7927">Ksenia Sorokina</a>&nbsp;(design),&nbsp;
                    <a href="https://www.facebook.com/profile.php?id=100001552140549">Alena Kuryanovich</a>&nbsp;(face of the game).</p>
                <p class="pull-right" align="middle">
                    <a href="https://twitter.com/mafiaonlinegame" title="We at Twitter" target='_blank'>
                        <img src="/img/twitter.png" align="middle" alt="We at Twitter" height="32" width="32" ></a>
                    <!-- <a href="https://www.facebook.com/pg/mafiaonlinegame/posts" title="We at Facebook" target='_blank'>
                        <img src="/img/facebook.png" align="middle" alt="We at Facebook" height="32" width="32" ></a> -->
                    &nbsp;&nbsp;&nbsp;&nbsp;<?= Yii::powered() ?>.</p>
            </div>
        </footer>

        <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>