frontend/controllers/SearchUsersController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace frontend\controllers;

use Yii;
use common\models\User;
use common\traits\CommonTrait;
use frontend\models\SearchUsersForm;
use frontend\models\ParticipantsForm;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * SearchController implements the CRUD actions for UserSearch model.
 */
class SearchUsersController extends Controller {

    /**
     * Lists all UserSearch models.
     *
     * @return mixed
     */
    public function actionIndex($viewOnlyPremium = null, $viewOnlyApprovedPhoto = null, $viewOnlyWithPhoto = null) {
        $additionalParams = ['viewOnlyPremium' => $viewOnlyPremium, 'viewOnlyApprovedPhoto' => $viewOnlyApprovedPhoto, 'viewOnlyWithPhoto' => $viewOnlyWithPhoto];
        $searchModel = new SearchUsersForm();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $additionalParams);

        return $this->render(
        'index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]
        );
    }

//end actionIndex()

    /**
     * Displays a single UserSearch model.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id) {
        $user = $this->findModel($id);
        CommonTrait::setGlobalsStatus($user->status);

        return $this->render(
        'view', ['model' => $user]
        );
    }

//end actionView()

    /**
     * Add a single UserSearch model to the table participant.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionAdd($id) {
        return $this->redirect(['/participants/create', 'id' => $id, 'redirectFromUsersSearch' => true]);
    }

//end actionAdd()

    /**
     * Block a single UserSearch model by adding to the table participant with category 'Blocked'.
     *
     * @param integer $id
     *
     * @return mixed
     */
    public function actionBlock($id) {
        $userToBlock = $this->findModel($id);
        $model = new ParticipantsForm();
        $model->scenario = ParticipantsForm::SCENARIO_CREATE;
        $model->participant = $userToBlock->username;
        $model->userId = Yii::$app->user->getId();
        $model->category = 'Blocked';
        try {
            $model->save();
            Yii::$app->session->setFlash('success', "User $userToBlock->username was blocked and can't be able to play or communicate with you.");
        } catch (ErrorException $e) {
            Yii::$app->session->setFlash('error', 'Oops... Something went wrong. There was server error during blocking user. Try again later. If the mistake will remain - please contact us.');

            return false;
        }

        return $this->redirect(['index']);
    }

//end actionBlock()

    /**
     * Finds the UserSearch model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     *
     * @param integer $id
     *
     * @return UserSearch the loaded model
     *
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

//end findModel()
}

//end class

frontend/controllers/SiteController.php
<?php

/** @author Kirill Lapchinsky rumatakira74@gmail.com */

namespace frontend\controllers;

use Yii;
use common\models\User;
use common\models\LoginForm;
use common\traits\CommonTrait;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\ChangePasswordForm;
use frontend\models\SignupForm;
use frontend\models\EditProfileForm;
use frontend\models\UpdatePhotoForm;
use frontend\models\DeleteAccountForm;
use frontend\models\ContactForm;
use frontend\models\SettingsForm;
use yii\base\InvalidParamException;
use yii\base\ErrorException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller.
 */
class SiteController extends Controller {

    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'login',
                    'logout',
                    'signup',
                ],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [
                            'login',
                            'signup',
                        ],
                        'allow' => false,
                        'ips' => CommonTrait::getBlockedIPs(),
                    // NOTE! With Yii 2.0.7 working only IPv6 addresses
                    ],
                    [
                        'actions' => [
                            'login',
                            'signup',
                        ],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

//end behaviors()

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => ['class' => 'yii\web\ErrorAction'],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

//end actions()

    /**
     * Redirecting user to the Signup if guest, or to the Gameplay page.
     */
    public function actionPlay() {
        if (\Yii::$app->user->isGuest) {
            return $this->redirect(['signup']);
        } else {
            return $this->redirect(['profile']);
        }
    }

//end actionPlay()

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex() {
        return $this->render('index');
    }

//end actionIndex()

    /**
     * Displays different site map pages for guests and users.
     *
     * @return mixed
     */
    public function actionSiteMap() {
        if (\Yii::$app->user->isGuest) {
            return $this->render('siteMapGuest');
        } else {
            return $this->render('siteMapUser');
        }
    }

//end actionSiteMap()

    /**
     * Displays contact page for guests.
     *
     * @return mixed
     */
    public function actionContact() {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(\Yii::$app->params['supportEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render(
            'contact', ['model' => $model]
            );
        }
    }

//end actionContact()

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) and $model->login()) {
            $user = Yii::$app->user->getIdentity();
            CommonTrait::setUserRoles($user);
            try {
                CommonTrait::participantsExplode($user);
                if ($user->status == 0) {
                    CommonTrait::statusRestore($user);
                    $user->save();
                    Yii::$app->session->setFlash('success', 'Welcome back ' . $user->username . '! Your account was restored!');
                }
            } catch (ErrorException $e) {
                $flash = array('error' => 'Oops... Something went wrong. There was server error during preparing operations. Try to reload the main page and login again. If the mistake will remain - please contact us.');

                self::actionLogout($flash);
            }

            return $this->goBack();
        } else {
            return $this->render(
            'login', ['model' => $model]
            );
        }//end if
    }

//end actionLogin()

    /**
     * Logs out the current user. Delete all rows with
     * current user->id from {{participants}}, i
     * mplode them and save to {{user}} [[participants]].
     *
     * @return mixed
     */
    public function actionLogout($flash = null) {
        $user = Yii::$app->user->getIdentity();
        if (CommonTrait::participantsImplode($user)) {
            $user->save();
        }

        Yii::$app->user->logout();
        if ($flash != null) {
            Yii::$app->session->setFlash(key($flash), current($flash));
        }

        return $this->goHome();
    }

//end actionLogout()

    /**
     * Prepare ActiveRecord object and renders user profile.
     */
    public function actionProfile() {
        $user = Yii::$app->user->identity;
        CommonTrait::setGlobalsStatus($user->status);


        return $this->render(
        'profile', ['model' => $user]
        );
    }

//end actionProfile()

    /**
     * Updates user profile.
     *
     * @return mixed
     */
    public function actionEditProfile() {
        $model = new EditProfileForm();
        if ($model->load(Yii::$app->request->post())) {
            $changesArray = $model->editProfile();

            if ($changesArray != null) {
                if ($changesArray['dataChanged']) {
                    if (!$changesArray['emailChanged'] and ! $changesArray['sexChanged']) {
                        Yii::$app->session->setFlash('success', 'Great! Your profile has been updated.');

                        return $this->redirect(['profile']);
                    } else if (!$changesArray['emailChanged'] and $changesArray['sexChanged']) {

                        return self::actionDeletePhoto();
                    }
                }

                return $this->redirect(['profile']);
            }
        }

        return $this->render(
        'editProfile', ['model' => $model]
        );
    }

//end actionEditProfile()

    /**
     * Mark user account for deletion.
     * 
     * @return mixed
     */
    public function actionDeleteAccount() {
        $model = new DeleteAccountForm();
        if ($model->load(Yii::$app->request->post()) && $model->deleteAccount()) {
            return self::actionLogout(['success' => 'Your account has been marked for deletion and will be deleted during next database cleaning procedure. Normally it happens monthly at the last days. Until that, you can restore your account by simply logging to the site.']);
        }

        return $this->render(
        'deleteAccount', ['model' => $model]
        );
    }
    
//end actionDeleteAccount()
    
    /**
     * Replace user photo in database with default image.
     * 
     * @return redirect /site/update-photo
     */
    public function actionDeletePhoto() {
        $user = Yii::$app->user->identity;
        CommonTrait::setBasePhoto($user);
        $user->save();

        return $this->redirect(['/site/update-photo']);
    }

//end actionDeletePhoto()

    /**
     * Updates user photo.
     *
     * @return mixed
     */
    public function actionUpdatePhoto() {
        $model = new UpdatePhotoForm();
        if ($model->load(Yii::$app->request->post()) and $model->editPhoto()) {
            Yii::$app->session->setFlash('success', 'Great! Your photo has been updated. In some browsers you need to refresh the page with cache cleaning (usually Ctrl-F5) to see all changes. ');

            return $this->refresh();
        }

        return $this->render(
        'updatePhoto', [
            'model' => $model,
            'userPhoto' => $model->user->photo
        ]
        );
    }

//end actionUpdatePhoto()



    /**
     * Renders user profile.
     * 
     * @return mixed
     */
    public function actionSettings() {
        $model = new SettingsForm();
        if ($model->load(Yii::$app->request->post()) && $model->updateSettings()) {
            return $this->refresh();
        }

        return $this->render(
        'settings', ['model' => $model]
        );
    }

//end actionSettings()

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup() {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                // if (Yii::$app->getUser()->login($user)) {
                if ($model->sendEmail($user)) {
                    $validateLink = Yii::$app->urlManager->createAbsoluteUrl(['site/resend-email', 'id' => $user->id, 'token' => $user->auth_key]);

frontend/views/search-users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\SearchUsersForm */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="search-users-by-email">

    <?php
    $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]);
    ?>

    <?= $form->field($model, 'email')->label('There are a lot of ways to find participants. First of all - you can search user by email:')->hint('Note! Not all users made their email viewable and searchable in the ' . Html::a('settings', ['site/settings']) . '. You can use more complex form below to find users.') ?>

    <div class="form-group">
        <?= Html::submitButton('Search user by email', ['class' => 'btn btn-main-red']) ?>
        <?= Html::a('Reset', ['index'], ['class' => 'btn btn-main-white']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/search-users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\SearchUsers */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Search users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="search-users-index" align=justify style="width:100%">
    <p>All users in the game divided in to two groups - your participants (blocked users also calculates as participants with category 'Blocked'), and all other users. User can be only in one of this groups at the same time.</p>
    <ul class="nav nav-tabs" role="tablist">
        <li><?= Html::a('Your participants', ['participants/index']) ?></li>
        <li class="active"><a role="tab" data-toggle="tab">Search users</a></li>
    </ul>

    </br>
    <?php echo $this->render('_search', ['model' => $searchModel]); ?>
    </br>
    <p>You can order results ascending or descending by pressing to the title links. To find users - type (can be grouped and not ended) in the blank fields, after each field press Enter. To reset form - press Reset button. To view user profile - press 'eye' tool, to add user to participants - press [+] ('add') tool. To block user - press [Ø] ('block') tool. To unblock user - just change or delete his/her category in your <?= Html::a('participants', ['participants/index']) ?>, also deletion from participants unblock user.</p>

    <h1><?= Html::encode('Search users') ?></h1>

    <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'tableOptions' => [
            'class' => 'table table-bordered'
        ],
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
            ],
            [
                'attribute' => 'photo',
                'format' => 'raw',
                'value' => function($data) {
                    return Html::a(Html::img("data:image/png;base64, $data->photo", ['alt' => 'User photo', 'class' => 'img-responsive']), ['/search-users/view', 'id' => $data->id]);
                },
            ],
            'username',
            //'email:email',
            [
                'attribute' => 'created_at',
                'format' => ['date', 'php:Y-m-d'],
            ],
            'first_name',
            'last_name',
            'sex',
            'birth_date',
            'country:ntext',
            'area:ntext',
            'city',
            [
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Tools',
                'template' => '{view}&nbsp{add}&nbsp{block}&nbsp{message}',
                'buttons' => [
                    'add' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-plus" title="Add"></span>', $url);
                    },
                    'block' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-ban-circle" title="Block"></span>', $url);
                    },
                    'message' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-comment" title="Message"></span>', $url);
                    },
                ],
            ],
        ],
    ]);
    ?>
    <p>
        <?= Html::a('Reset', ['index'], ['class' => 'btn btn-main-white']) ?>
        <?= Html::a('Cancel', ['/site/index'], ['class' => 'btn btn-main-white']) ?>
        <?= Html::a('View only premium users', ['index', 'viewOnlyPremium' => 'true'], ['class' => 'btn btn-main-white']) ?>
        <?= Html::a('View only users with approved photo', ['index', 'viewOnlyApprovedPhoto' => 'true'], ['class' => 'btn btn-main-white']) ?>
        <?= Html::a('View only users with photo', ['index', 'viewOnlyWithPhoto' => 'true'], ['class' => 'btn btn-main-white']) ?>
    </p>
</div>

frontend/views/search-users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\SearchUserForm */

$this->params['breadcrumbs'][] = ['label' => 'Users list', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'View user:';
?>

<div class="search-users-view">
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div align=center>
                <?= Html::img("data:image/png;base64, $model->photo", ['alt' => 'User photo', 'class' => 'img-responsive']) ?>
            </div>
            <div>
                </br>

                <?php if ($model->show_email == 0) : ?>

                    <?=
                    DetailView::widget([
                        'options' => [
                            'class' => 'table table-bordered'
                        ],
                        'model' => $model,
                        'attributes' => [
                            'username',
                            [
                                'attribute' => 'status',
                                'value' => Html::tag('font', Html::encode($GLOBALS['userStatus']), ['color' => $GLOBALS['statusColor']]),
                                'format' => 'raw',
                            ],
                            'created_at:datetime',
                            'updated_at:datetime',
                            'first_name',
                            'last_name',
                            'sex',
                            'birth_date:date',
                            'country',
                            'area',
                            'city',
                        ],
                    ])
                    ?>

                <?php else : ?>

                    <?=
                    DetailView::widget([
                        'options' => [
                            'class' => 'table table-bordered'
                        ],
                        'model' => $model,
                        'attributes' => [
                            'username',
                            'email:email',
                            [
                                'attribute' => 'status',
                                'value' => Html::tag('font', Html::encode($GLOBALS['userStatus']), ['color' => $GLOBALS['statusColor']]),
                                'format' => 'raw',
                            ],
                            'created_at:datetime',
                            'updated_at:datetime',
                            'first_name',
                            'last_name',
                            'sex',
                            'birth_date:date',
                            'country',
                            'area',
                            'city',
                        ],
                    ])
                    ?>

                <?php endif; ?>
            </div>
            <div class="form-group">
                <p>
                    <?= Html::a('Cancel', ['index'], ['class' => 'btn btn-main-white']) ?>
                    <?= Html::a('Add to participants', ['add', 'id' => $model->id], ['class' => 'btn btn-main-white']) ?>
                </p>
            </div>
        </div>
        <div align=right class="col-xs-12 col-md-4" style="class: img-responsive">
            <p>
                <a href="http://donate.unhcr.org/international/general" title="UN Refugee Agency" target='_blank'>
                    <img src="/img/banners/UNHCR/WRD2015-300x600-V2-Nader.jpg" alt="UN Refugee Agency" >
                </a>
            </p>
        </div>
        <div align=right class="hidden-xs col-md-4" style="class: img-responsive">
            <p>
                <a href="http://www.unhcr.org" title="UN Refugee Agency" target='_blank'>
                    <img src="/img/banners/UNHCR/WRD2015-300x600-V2-Katia.jpg" alt="UN Refugee Agency" >
                </a>
            </p>
        </div>
    </div>
</div>